apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mea

resources:
  - namespace.yaml
  - app-config.yaml
  - app-secret.yaml
  - strangler-proxy.yaml
  - review-service.yaml
  - notification-service.yaml
  - inventory-service.yaml
  - payment-service.yaml
  - shipping-service.yaml
  - order-service.yaml
  - graphql-gateway.yaml
  - infra/postgres-statefulset.yaml
  - infra/kafka-statefulset.yaml
